### ISSUE TITLE
Jest has limitations as testing framework

### ISSUE THREAD

**Issue by johnolos** [Pubcrawler/old-pubcrawler-api#9]
Jest proves to be a slight difficult to be used as our main testing framework.

Fairly easy rest-api testing framework such as `supertest` and `chai` with `chai-http` work much better with mocha or jasmine.

I propose a switch to mocha for at least `pubcrawler-api` as the testing needs are a little different than those in `pubcrawler-frontend`.

**Comment by hawkaa** [comment]
I have experience with supertest, and it's a great tool, so we should probably use that. If it doesn't work with jest (like here https://gist.github.com/pgericson/e7020f419b13aa0dcc5c0a3be35f7c6c), we should probably switch to something else. 

I propose mocha over jasmine. No particular justification, just a gut feeling of what people normally use "out there".
